apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: docker.io/bankolejohn/ignite-nodejsapp:1.0 # Replace with your Node.js app image
        ports: 
        - containerPort: 3000 # Port your Node.js app is listening on
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app  # This should match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80      # Port exposed by the Service (can be any port)
      targetPort: 3000  # Port your Node.js app is listening on
  type: ClusterIP    # Change to NodePort or LoadBalancer as needed
