name: CI/CD with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t newimage .

    - name: Push Docker Image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker tag newimage "${{ secrets.DOCKER_HUB_USERNAME }}/newimage:latest"
        docker push "${{ secrets.DOCKER_HUB_USERNAME }}/newimage:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
          unzip terraform_0.15.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Deploy Docker Image
        run: |
          terraform init
          terraform apply -auto-approve

          # Extract the public IP of the deployed EC2 instance
          instance_ip=$(terraform output instance_public_ip)

          # Example: Deploy Docker image on EC2 using SSH
          docker save your-docker-image-name | ssh -o StrictHostKeyChecking=no ubuntu@${instance_ip} 'docker load'

          # Clean up (destroy resources)
          #terraform destroy -auto-approve
